alias emacs="/Applications/Emacs.app/Contents/MacOS/Emacs -nw"
alias emacsclient="/Applications/Emacs.app/Contents/MacOS/bin/emacsclient"
alias em=$PRE"/dotfiles/scripts/emacsclienthelper.sh"
alias ctags="/usr/local/bin/ctags"
alias updatedb="sudo /usr/libexec/locate.updatedb"
alias tabnm=$PRE"/dotfiles/scripts/tabnm.sh"
alias dirs="dirs -v"
