
(defun sweyla739202 ()
  "Theme generated by Sweyla: http://themes.sweyla.com/seed/739202/"
  (interactive)
  (color-theme-install
   '(sweyla739202
     ((background-color . "#030409")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#FF6178"))))
     (font-lock-constant-face ((t (:foreground "#FF0054"))))
     (font-lock-builtin-face ((t (:foreground "#8700A9"))))
     (font-lock-function-name-face ((t (:foreground "#FF2C9D"))))
     (font-lock-variable-name-face ((t (:foreground "#C40C49"))))
     (font-lock-keyword-face ((t (:foreground "#A6D8FD"))))
     (font-lock-string-face ((t (:foreground "#6C009B"))))
     (font-lock-doc-string-face ((t (:foreground "#6C009B"))))
     (font-lock-type-face ((t (:foreground "#FFEF8C"))))
     )))

(provide 'sweyla739202)
