
(defun sweyla665776 ()
  "Theme generated by Sweyla: http://themes.sweyla.com/seed/665776/"
  (interactive)
  (color-theme-install
   '(sweyla665776
     ((background-color . "#00000B")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#AD1E1C"))))
     (font-lock-constant-face ((t (:foreground "#C7FF1E"))))
     (font-lock-builtin-face ((t (:foreground "#B78291"))))
     (font-lock-function-name-face ((t (:foreground "#9C5D7E"))))
     (font-lock-variable-name-face ((t (:foreground "#6B8951"))))
     (font-lock-keyword-face ((t (:foreground "#FF470B"))))
     (font-lock-string-face ((t (:foreground "#B12B0C"))))
     (font-lock-doc-string-face ((t (:foreground "#B12B0C"))))
     (font-lock-type-face ((t (:foreground "#9D6C0C"))))
     )))

(provide 'sweyla665776)
