
(defun sweyla604352 ()
  "Theme generated by Sweyla: http://themes.sweyla.com/seed/604352/"
  (interactive)
  (color-theme-install
   '(sweyla604352
     ((background-color . "#000200")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#FFB5CC"))))
     (font-lock-constant-face ((t (:foreground "#35BE1B"))))
     (font-lock-builtin-face ((t (:foreground "#387788"))))
     (font-lock-function-name-face ((t (:foreground "#45BE00"))))
     (font-lock-variable-name-face ((t (:foreground "#947100"))))
     (font-lock-keyword-face ((t (:foreground "#3DC200"))))
     (font-lock-string-face ((t (:foreground "#F70000"))))
     (font-lock-doc-string-face ((t (:foreground "#F70000"))))
     (font-lock-type-face ((t (:foreground "#2347A7"))))
     )))

(provide 'sweyla604352)
