
(defun sweyla347099 ()
  "Theme generated by Sweyla: http://themes.sweyla.com/seed/347099/"
  (interactive)
  (color-theme-install
   '(sweyla347099
     ((background-color . "#FFFFFF")
      (foreground-color . "#000000")
      (background-mode . bright)
      (border-color . "#C8C8C8")
      (cursor-color . "#000000")
      (mouse-color . "#C8C8C8"))
     (mode-line ((t (:foreground "#000000" :background "#C8C8C8"))))
     (region ((t (:background "#C8C8C8"))))

     (font-lock-comment-face ((t (:foreground "#4B3900"))))
     (font-lock-constant-face ((t (:foreground "#411E34"))))
     (font-lock-builtin-face ((t (:foreground "#687A35"))))
     (font-lock-function-name-face ((t (:foreground "#4C008F"))))
     (font-lock-variable-name-face ((t (:foreground "#E82F6D"))))
     (font-lock-keyword-face ((t (:foreground "#C5161C"))))
     (font-lock-string-face ((t (:foreground "#911491"))))
     (font-lock-doc-string-face ((t (:foreground "#911491"))))
     (font-lock-type-face ((t (:foreground "#C46888"))))
     )))

(provide 'sweyla347099)
