
(defun sweyla662432 ()
  "Theme generated by Sweyla: http://themes.sweyla.com/seed/662432/"
  (interactive)
  (color-theme-install
   '(sweyla662432
     ((background-color . "#000805")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#88D47A"))))
     (font-lock-constant-face ((t (:foreground "#EC7E43"))))
     (font-lock-builtin-face ((t (:foreground "#AFDD7F"))))
     (font-lock-function-name-face ((t (:foreground "#E9FF80"))))
     (font-lock-variable-name-face ((t (:foreground "#C1522E"))))
     (font-lock-keyword-face ((t (:foreground "#0FFF16"))))
     (font-lock-string-face ((t (:foreground "#729896"))))
     (font-lock-doc-string-face ((t (:foreground "#729896"))))
     (font-lock-type-face ((t (:foreground "#87FF32"))))
     )))

(provide 'sweyla662432)
